# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: DecisionEvent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'DecisionEvent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x44\x65\x63isionEvent.proto\x12\x08\x61\x65quitas\"\x93\x01\n\rDecisionEvent\x12\x14\n\x0c\x61pplicant_id\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0c\n\x04race\x18\x03 \x01(\x05\x12\x0b\n\x03sex\x18\x04 \x01(\x05\x12\x10\n\x08\x64\x65\x63ision\x18\x05 \x01(\x05\x12\x1c\n\x14\x61pproval_probability\x18\x06 \x01(\x01\x12\x14\n\x0ctimestamp_ms\x18\x07 \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DecisionEvent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DECISIONEVENT']._serialized_start=34
  _globals['_DECISIONEVENT']._serialized_end=181
# @@protoc_insertion_point(module_scope)
